# Generated by Django 3.2 on 2022-08-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uname',
            new_name='username',
        ),
    ]
